### ISSUE TITLE
a misregistered package action-cable

### ISSUE THREAD

**Issue by hardywu** [bower/registry#172] opened 2016-02-12 16:35 UTC
Hi, guys. 

I am trying to register a package `action-cable` for actioncable from Ruby on Rails. But the name `action-cable` is misregistered  to another package `action-cable-react`. And I cannot delete the name `actioncable` that I registered by mistake either. 

```bash
$ bower search action-cable                    
Search results:

    action-cable-bower git://github.com/hardywu/action-cable.git
    actioncable git://github.com/hardywu/action-cable.git
    action-cable git://github.com/schneidmaster/action-cable.git
    action-cable-react git://github.com/schneidmaster/action-cable-react.git

$ bower unregister actioncable 
? You are about to remove component "actioncable" from the bower registry (https://bower.herokuapp.com). It is generally considered bad behavior to remove versions of a library that others are depending on. Are you really sure? Yes
bower unregister    actioncabler to remove versions of a library that others are depending on. Are you really subower EUNKNOWN      <!DOCTYPE html>     <html>     <head>       <meta name="viewport" content="width=device-width, initial-scale=1">       <style type="text/css">         html, body, iframe { margin: 0; padding: 0; height: 100%; }         iframe { display: block; width: 100%; border: none; }       </style>     <title>Application Error</title>     </head>     <body>       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">         <p>Application Error</p>       </iframe>     </body>     </html>
```

**Comment by BenMann** [comment] 2016-02-12 19:56
Closing in favor of https://github.com/bower/bower/issues/2171.
Unregistering should work again, once that is resolved.

**Closed by BenMann** 2016-02-12 19:56 UTC

**Comment by BenMann** [comment] 2016-02-14 07:00
You should now be able to unregister packages as intended. :tada:

**Comment by hardywu** [comment] 2016-02-14 19:15
Thanks a lot.
